# Generated by Django 5.0 on 2023-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('machine_name', models.CharField(max_length=32)),
                ('location_long', models.CharField(max_length=32)),
                ('location_lat', models.CharField(max_length=32)),
            ],
        ),
    ]
