# Generated by Django 5.0 on 2024-01-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='icon',
            field=models.IntegerField(default=0),
        ),
    ]
